# Change these first
owner: jpwahle # Your GitHub organization or username, where this repository lives
repo: cs-insights-uptime # The name of this repository

sites:
  - name: Frontend
    url: http://cs-insights.uni-goettingen.de
  - name: Backend
    url: http://cs-insights.uni-goettingen.de/api/v0/status
  - name: Prediction-Endpoint
    url: http://cs-insights.uni-goettingen.de:8000/api/v0/status
assignees:
  - jpwahle
  - truas
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: cs-insights-uptime
  logoUrl: https://raw.githubusercontent.com/jpwahle/cs-insights-main/main/images/logo-with-text.png
  name: cs-insights-uptime
  introTitle: "This uptime monitor tracks services of the cs-insights project and generates a status page powered entirely by GitHub actions."
  introMessage: This status page uses **real-time** data from GitHub to track the endpoints of the cs-insights project.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
